@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

SHOW_PERSON_OUTLINE()

Person("r", "Reiziger", "Stelt reis samen en boekt deze")
Person("ra", "Reisagent", "Helpt reiziger wanneer dat nodig is")


System_Boundary("naam", "Titel"){
    Container("be", "Backend", "Handelt requests vanuit de frontend af")
    Container("fe", "Triptop-applicatie", "Frontend van reisapplicatie die reizigers kunnen gebruiken")
    Container("db", "Database", "Worden geboekte reizen in opgeslagen")
}

System_Ext("sg", "Sendgrid", "Kan mails sturen naar relevante actoren")
System_Ext("as", "airscraper", "Vindt beschikbare vluchten")
System_Ext("eur", "Interrail/Eurail", "Vindt beschikbare treinreizen binnen Europa")
System_Ext("wm", "Wiremock", "Identityprovider, laat mensen inloggen")
System_Ext("tw", "Twilio", "Kan berichten naar telefoonnummers van reizigers sturen")
System_Ext("ta", "Tripadvisor", "Vindt informatie over hotels en dergelijke")
System_Ext("st", "Stripe", "Laat reizeigers betalen")
System_Ext("gm", "Google Maps", "Laat reizigers zien wat de locatie is van de dingen waar ze heen willen")


Rel("r", "fe", " ")
Rel("ra", "fe", " ")
Rel("fe", "be", " ")
Rel("be", "db", " ")

Rel("be", "sg", " ")
Rel("be", "as", " ")
Rel("be", "eur", " ")
Rel("be", "wm", " ")
Rel("be", "tw", " ")
Rel("be", "ta", " ")
Rel("be", "st", " ")
Rel("fe", "gm", " ")


'todo: labels bij de pijltjes bedenken




@enduml