@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Component(tep, "TravelExpensePro", "Dit is de main applicatie")

Component(emc, "ExpenseManagementController", "Handelt in- en uitloggen af")
Component(ec, "ExpenseController", "Laat de gebruiker expenses toevoegen en expensen ophalen")

Component(er, "ExpenseRepository", "")
Component(ur, "UserRepository", "")
Component(as, "AuthenticationService", "")

Rel(emc, tep, " ")
Rel(ec, tep, " ")

Rel(tep, er, " ")
Rel(tep, ur, " ")
Rel(tep, as, " ")



@enduml