@startuml

package Hotel{
    class HotelAdapter{
    - API_KEY
    - SAVE_API_URL
    - GET_API_URL
    + saveData(hotelData)
    + retrieveData(hotelData): 
    }

    class HotelRepo{
    - bookings: List<HotelBooking>
    + save(hotelBooking)
    + findById(id): HotelBooking
    + findAll(): List<HotelBooking>
    }

    class HotelController{
    - HotelService
    + getHotels()
    + getHotel()
    + boekHotel()
    }

    class HotelService{
    - HotelRepo
    - BookingStrategy
    + saveHotelBooking(hotelBooking)
    + getHotelBooking(): HotelBooking
    + getHotelBookings(): HotelBooking
    }
}

package Trip{
    class TripAdapter{
    - API_KEY
    - SAVE_API_URL
    - GET_API_URL
    + saveData(tripData)
    + retrieveData(tripData)
    }

    class TripRepo{
    + save(tripBookingen)
    + findById(): TripBooking
    + findAll(): List<TripBooking>
    }

    class TripController{
    - TripService
    + getTrips()
    + getTrip()
    + boekTrip()
    }

    class TripService{
    - TripRepo
    - BookingStrategy
    + saveTripBooking()
    + getTripBooking()
    + getTripBookings()
    }
}




HotelController --> HotelService : uses
TripController --> TripService : uses

HotelService --> HotelRepo : uses
TripService --> TripRepo : uses

HotelService --> HotelAdapter : uses
TripService --> TripAdapter : uses





@enduml