@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Sequence.puml

Container(Triptop, "Triptop", "Frontend")
Component(BouwsteenController, "BouwsteenController", "", "Beheert bouwstenen")
Component(BouwsteenService, "BouwsteenService", "", "Behandelt bouwsteen logica")
Component(BouwsteenFactory, "BouwsteenFactory", "", "Creëert Bouwsteen objecten")
Component(BouwsteenRepository, "BouwsteenRepository", "", "Slaat bouwstenen op")

Rel(Triptop, BouwsteenController, "Verstuurt request voor toevoegen bouwsteen", "JSON/HTTP")
BouwsteenController -> BouwsteenService : createBouwsteen(factory, details)
BouwsteenService -> BouwsteenFactory : Bouwsteen bouwsteen = createBouwsteen(details)
BouwsteenService -> BouwsteenRepository : save(bouwsteen)
@enduml
