@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Sequence.puml

Container(tt, "Triptop", "Frontend")
Component(bc, "BouwsteenController", "Beheert bouwstenen")
Component(ss, "ServiceStrategy", "Behandelt bouwsteen logica")
Component(bs, "Bouwsteen", "Is een bouwsteen")
Component(br, "BouwsteenRepo", "Behandelt database-related logica voor bouwstenen")

Rel(tt, bc, "Request voor opslaan bepaald type bouwsteen", "JSON/HTTP")
Rel(bc, bc, "Juiste strategy wordt gekozen")
Rel(bc, bs, "setDetails(details)", "Details van bouwsteen worden aan instantie toegevoegd")
Rel(bc, ss, "saveBouwsteen(Bouwsteen)")
Rel(ss, bs, "saveBouwsteen(Bouwsteen)")
Rel(bs, br, "saveBouwsteen(Bouwsteen)")





@enduml
