@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Sequence.puml

actor Reiziger

Component(BouwsteenController, "BouwsteenController", "", "Beheert bouwstenen")
Component(BouwsteenService, "BouwsteenService","", "Behandelt bouwsteen logica")
Component(BouwsteenRepository, "BouwsteenRepository","", "Slaat bouwstenen op")
Component(TripService, "TripService","", "Beheert trip gerelateerde bouwstenen")
Component(ApiService, "ApiService","", "Boekt overnachtingen en vervoer")

Reiziger -> BouwsteenController : Create Bouwsteen(type, details)
BouwsteenController -> BouwsteenService : Bouwsteen bouwsteen = createBouwsteen(type, details)
BouwsteenService -> BouwsteenRepository : save(bouwsteen)

Reiziger -> TripService : Add Bouwsteen to trip(tripId, bouwsteen)
TripService -> BouwsteenService : Bouwsteen bouwsteen = getBouwsteenById(bouwsteenId)

Reiziger -> ApiService : Book Accommodation (overnachting)

@enduml
