@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Component("bc", "BouwsteenController", "controller voor alle bouwstenen")
Component("hr", "HotelRepo", "Repo voor hotel bouwsteen")
Component("tr", "TripRepo", "Repo voor trip bouwsteen")
Component("bsf", "BouwsteenFactory", "Maakt instanties van bouwstenen aan.")
Component("hs", "HotelService", "Service voor hotel bouwsteen")
Component("ts", "TripService", "Service voor trip bouwsteen")


Component_Ext("aa","adapterAirbnb", "API")
Component_Ext("ab","adapterBookingcom", "API")

Component_Ext("tapi","TripAPIS", "API's voor trip bouwsteen")

System("db", "Database")

Rel("hs", "ab", " ")
Rel("hs", "aa", " ")

Rel("bc", "hs", " ")
Rel("bc", "ts", " ")

Rel("hs", "bsf", " ")
Rel("ts", "bsf", " ")

Rel("ts", "tr", " ")
Rel("hs", "hr", " ")

Rel("ts", "tapi", " ")

Rel("tr", "db", " ")
Rel("hr", "db", " ")


@enduml
