@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Sequence.puml

Container(c1, "Triptop", "Frontend-applicatie")
Container(c2, "Backend", "Backend-applicatie")
Container(c3, "Wiremock", "Identity provider")
Container_Ext(c4, "Externe APIs", "Geven informatie van derde partijen die gebruikt kan worden bij het boeken van een reis")
Container(c5, "Database", "Slaat geboekte reizen op")


Rel(c1, c2, "Verstuurt request voor boeking reis", "JSON/HTTP")
Rel(c2, c3, "Valideert token")
Rel(c2, c4, "Reserveert alles aangaande de reis", "JSON/HTTP")

Rel(c4, c2, "Stuurt boekingsgegevens terug", "JSON/HTTP")
Rel(c2, c5, "Slaat boekingsgegevens op", "NoSQL")
Rel(c2, c1, "Bevestiging boeking en bijbehorende gegevens", "JSON/HTTP")

@enduml