@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component Diagram voor TripTop (Makkelijk toevoegen externe service)

System_Boundary("backend", "Backend") {
    Component(TripController, "TripController", "Beveiligde toegang tot backend")
    Component(interface, "Interface", "Standaard contract")
    Component(adapter, "Adapter", "Communiceert met externe services")
    Component(handler, "ExternalServiceHandler", "Handelt externe service-verzoeken af")
    Component(TripRepo, "TripRepo", "Verbinding met database")
}

System_Boundary("database", "Database") {
    System(db, "Database", "Opslag van gegevens")
}

System_Boundary("APIS", "APIS") {
    System(API, "externeAPI", "")
}

Rel(TripController, interface, "Verzendt beveiligde verzoeken naar")
Rel(interface, handler, "Routeert verzoeken naar")
Rel(handler, "adapter", "Implementeert communicatie met externe services")
Rel("handler", "TripRepo", "Verbinding met database")
Rel("adapter", API, "Stuurt request")
Rel("TripRepo", db, "Leest/Schrijft data naar")

@enduml
