@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Component("bc", "BouwsteenController", "controller voor alle bouwstenen")
Component("hr", "HotelRepo", "Repo voor hotel bouwsteen")
Component("tr", "TripRepo", "Repo voor trip bouwsteen")
Component("bsf", "BouwsteenFactory", "Maakt instanties van bouwstenen aan.")
Component("hs", "HotelService", "Service voor hotel bouwsteen")
Component("ts", "TripService", "Service voor trip bouwsteen")


Component_Ext("aa","adapterAirbnb", "API")
Component_Ext("ab","adapterBookingcom", "API")

Component_Ext("tapi","TripAPIS", "API's voor trip bouwsteen")

System("db", "Database")

Rel("hs", "aa", " ")

Rel("bc", "hs", "Roept methoden aan in HotelService.")
Rel("bc", "ts", "Roept methoden aan in TripService.")

Rel("hs", "bsf", "Gebruikt factory om bouwstenen aan te maken.")
Rel("ts", "bsf", "Gebruikt factory om bouwstenen aan te maken.")

Rel("ts", "tr", "verstuurt bouwstenen")
Rel("hs", "hr", "verstuurt bouwstenen")

Rel("ts", "tapi", "Verstuurt aanvragen naar Trip API's ")
Rel("hs", "ab", "Verstuurt aanvragen naar API's ")

Rel("tr", "db", "Haalt/ stuurt data op")
Rel("hr", "db", "Haalt/ stuurt data op")


@enduml
